# Scalar Quantization

In [8]:
import numpy as np

dataset = np.array([1.23, 1.62, 0.76, -0.93])

# Calculate and store minimum and maximum across each dimension
ranges = np.vstack((np.min(dataset, axis=0), np.max(dataset, axis=0)))

In [9]:
starts = ranges[0,:]
steps = (ranges[1,:] - ranges[0,:]) / 255

In [14]:
scalar_quantized_dataset = np.uint32((dataset - starts) / steps)

In [15]:
dataset

array([ 1.23,  1.62,  0.76, -0.93])

In [16]:
scalar_quantized_dataset

array([216, 255, 169,   0], dtype=uint32)

# Product Quantization

In [ ]:
array = [ [ 8.2, 10.3, 290.1, 278.1, 310.3, 299.9, 308.7, 289.7, 300.1],
				[ 0.1, 7.3, 8.9, 9.7, 6.9, 9.55, 8.1, 8.5, 8.99] ]

In [ ]:
quantized_array = [[ 0  0 14 13 15 14 14 14 14]
								 [ 0  0  0  0  0  0  0  0  0]]

In [6]:
from sklearn.cluster import KMeans
import numpy as np

# Given array
array = np.array([
    [8.2, 10.3, 290.1, 278.1, 310.3, 299.9, 308.7, 289.7, 300.1],
    [0.1, 7.3, 8.9, 9.7, 6.9, 9.55, 8.1, 8.5, 8.99]
])

# Number of subvectors and centroids
m, k = 3, 2

# Divide each vector into m disjoint sub-vectors
subvectors = array.reshape(-1, m)

# Perform k-means on each sub-vector independently
kmeans = KMeans(n_clusters=k, random_state=0).fit(subvectors)

# Replace each sub-vector with the index of the nearest centroid
labels = kmeans.labels_

# Reshape labels to match the shape of the original array
quantized_array = labels.reshape(array.shape[0], -1)

# Output the quantized array
quantized_array

array([[0, 1, 1],
       [0, 0, 0]])